apiVersion: apps/v1
kind: Deployment
metadata:
  name: combined-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined-service
  template:
    metadata:
      labels:
        app: combined-service
    spec:
      containers:
      - name: combined-service
        image: vineelam23/combined-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002

---

apiVersion: v1
kind: Service
metadata:
  name: combined-service
spec:
  selector:
    app: combined-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: NodePort
