apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world-service
  template:
    metadata:
      labels:
        app: world-service
    spec:
      containers:
      - name: world-service
        image: vineelam23/world-service:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: world-service
spec:
  selector:
    app: world-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30544
  type: NodePort


